name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        include:
#          - python-version: "3.9"
#            tox-env: py39
          - python-version: "3.12"
            tox-env: py312
        os:
          - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Conventional Commits
        uses: webiny/action-conventional-commits@v1.1.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: 'pyproject.toml'

      - uses: actions/cache@v3.3.1
        with:
          path: |
            .tox
          key: imgzen-${{ matrix.python-version }}-v1-${{ hashFiles('pyproject.toml') }}
          restore-keys: imgzen-${{ matrix.python-version }}-v1-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox environment
        run: tox -e ${{ matrix.tox-env }}

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tox
        run: pip install tox

      - name: Run lint
        run: tox -e lint

  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tox
        run: pip install tox

      - name: Run pre-commit hooks
        run: tox -e pre-commit
